### ISSUE TITLE
Scrolling problem

### ISSUE THREAD

**Issue by Navakanth09** [vladexologija/PinterestListView#3]
when the height of leftlistview is more than rightlistview I can scroll only upto the height of rightlistview, in leftlistview I can't scroll to the items below the height of rightlistview

**Comment by vladexologija** [comment]
Hey Navakanth,

Sorry unfortunately I have been very busy and I don't have much time to focus on PintrestListView.
I'm planning to build v2 which will be the real library and have these issues resolved. 
Pull Requests are very welcome however!

Thanks,
Vladimir
